### ISSUE TITLE
Feature Request: Filter by supported nips

### ISSUE THREAD

**Issue by chmac** [sandwichfarm/nostr-watch#198]
**Is your feature request related to a problem? Please describe.**
I'm looking for relays which support nip33.

**Describe the solution you'd like**
It would be great to have the option to filter the list of relays by a specific NIP they support. Or even multiple. So I could say "show me relays that support nip16 and nip33" for example.

**Describe alternatives you've considered**
I can click into and out of each relay one at a time. Definitely does work. :-)

Thanks for nostr-watch, it's great. 🧡

**Comment by dskvr** [comment]
Hey there! I started on this a while ago, but other things took precedent. 

I have an api that returns relays based on nip support, but haven't released it. 

Thanks for submitting this, as it wasn't already an issue.

Cheers!

**Comment by cj-chua** [comment]
> **Is your feature request related to a problem? Please describe.** I'm looking for relays which support nip33.
> 
> **Describe the solution you'd like** It would be great to have the option to filter the list of relays by a specific NIP they support. Or even multiple. So I could say "show me relays that support nip16 and nip33" for example.
> 
> **Describe alternatives you've considered** I can click into and out of each relay one at a time. Definitely does work. :-)
> 
> Thanks for nostr-watch, it's great. 🧡

+1, this feature would be awesome for nostr client/app developers!

**Comment by dskvr** [comment]
Working on a release that has many cross-dependencies, and a little behind because I got sick for a few days. Once it is released, this will be next up.

**Comment by dskvr** [comment]
This feature is live on [staging](https://next.nostr.watch ).

![Screen Shot 2023-02-10 at 7 50 24 PM](https://user-images.githubusercontent.com/299465/218173711-6f5e285a-40f1-4be8-a6a9-f39a491de55f.png)

**Comment by dskvr** [comment]
Also, the API I mentioned [here](https://github.com/dskvr/nostr-watch/issues/198#issuecomment-1382308341) was reluctantly deployed a week or so ago here: https://api.nostr.watch

**Comment by chmac** [comment]
@dskvr I'm struggling to find the filters that you're showing in that screenshot on https://next.nostr.watch/relays/find. It looks great in the screenshot though, even better than I had in mind! :-)

Being able to filter by multiple NIPs would be awesome, so I can say I need nips 9, 33, and 40 etc.

**Comment by dskvr** [comment]
[chmac](https://github.com/chmac) Sorry I missed this, the filters only show after the relays have been checked. There are too many potential issues, unpredictability and confusion that is introduced when filters are enabled before data is loaded. If "Client-Side Processing" is enabled, this is a much bigger issue than if it's disabled, since historical relay results are 99% faster (a couple seconds)
