### ISSUE TITLE
Enable Tor tab on Clearnet

### ISSUE THREAD

**Issue by dskvr** [sandwichfarm/nostr-watch#270]
**Is your feature request related to a problem? Please describe.**
No tor relays listed 

**Describe the solution you'd like**
- Add `relays.tor.yaml`
- Don't discard onion addresses in prebuild `discovery` 
- Use `relay.tor` member to filter onion addresses.
- Show onion addresses (without status checks) on clearnet. 

**Describe alternatives you've considered**
Complementary, not alternative: #269

**Comment by bleetube** [comment]
Here's mine for when this drops:

`ws://bitcoinr6de5lkvx4tpwdmzrdfdpla5sya2afwpcabjup2xpi5dulbad.onion` (bitcoiner.social relay)
