### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by mdavids** [sandwichfarm/nostr-watch#308]
**Is your feature request related to a problem? Please describe.**
Not a problem as such, but it would be nice if relays are tested on their IPv6 address too (because it might be dual stacked and working on IPv4, but not on IPv6, which could lead to problems).

**Describe the solution you'd like**
Besides IPv4 addresses in the detailed dashboard, also show IPv6 availability. Perhaps even in the main dashboard?

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by dskvr** [comment]
nostr.watch uses the cloudflare DOH resolver to detect DNS. According to [these docs](https://developers.cloudflare.com/1.1.1.1/infrastructure/ipv6-networks/), it should be possible, however, when I was attempting to complete this a while back (you're not the first to ask), I kept hitting roadblocks. I was timeboxed and had to move on. I will revisit when I'm not in the middle of a release. 

cheers!

**Comment by dskvr** [comment]
Additionally, the IP-API of choice (the one that's affordable and has robust support for client-side apps) does not support IPv6 (probably not ever), so the Geo Data would need to be queried based on IPv4.

**Comment by mdavids** [comment]
> nostr.watch uses the cloudflare DOH resolver to detect DNS. According to [these docs](https://developers.cloudflare.com/1.1.1.1/infrastructure/ipv6-networks/), it should be possible

That link refers to DNS64 (and consequently NAT64), which is not what I meant. I'm talking 'native IPv6 connectivity', so just do an ['AAAA' query](https://toolbox.googleapps.com/apps/dig/#AAAA/) besides an ['A' query](https://toolbox.googleapps.com/apps/dig/#A/). Geolocation is something else. I suppose I could live with a page that would only show the geolocation of the IPv4 address.
