### ISSUE TITLE
Max latency/last hour is a good parameter

### ISSUE THREAD

**Issue by serrq** [sandwichfarm/nostr-watch#338]
In nostr.watch website will be useful see the max latency value in the last hour and in the last 12 hours.

These are good parameters because show the health of the service.

Of course sorted from lower to higher.

**Comment by dskvr** [comment]
I'll think about how to implement this, thanks!

**Comment by pfergi42** [comment]
Don't these latency numbers entirely depend on where the nostr.watch server is located? Relays closer to nostr.watch geographically will naturally have lower latency readings, is that right?
