### ISSUE TITLE
Add Icons & Icons Column 

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#344]
**Is your feature request related to a problem? Please describe.**
It is difficult to remember the names of the hundreds and increasing various relays. Many of them sound the same  - relay, nostr etc. 

**Describe the solution you'd like**
Propose to add a new column to nostr.watch that would display the relay's favicon. Currently very few relays utilize the favicon functionality. One of the few examples is https://nostr.wine/favicon.ico. 
![image](https://user-images.githubusercontent.com/64376233/217328849-2f22257d-24ac-476d-910e-92c642c97910.png)

Favicons are typically stored as follows: e.g. wss://relay.damus.io/ -> https://relay.damus.io/favicon.ico. 

By displaying relays with favicon on nostr.watch, it will become apparent which relay operators are paying attention to user requests, which allow them to build brand recognition. I expect with time there will be strongly branded relays, similar to how there are branded mobile phone carriers.

**Describe alternatives you've considered**
Don't do anything/keep status quo.

**Additional context**
If nostr.watch helps increase relay adoption of favicons by displaying who has or does not have favicons, in turn nostr clients could enable relay settings that include icons. 30 second client mockup:
![image](https://user-images.githubusercontent.com/64376233/217329305-80a4f417-85e7-4263-87a1-86e23b96dbaa.png)

https://github.com/nostr-protocol/nostr/issues/128

**Comment by dskvr** [comment]
I can potentially add this as an extension to favorites

**Comment by dskvr** [comment]
> Is it possible and worthwhile to query all the relay's http:// websites for the favicon.ico standard format + URL?

Yes, this is what is done for NIP-11, SSL checks, etc. However, in my tests yesterday, I got a total of 0 icons out of 400 relays I tested. In order for there to be a "nudge" there would need to first be some relays that have favicons.
