### ISSUE TITLE
Minor UI Fix - Hover Over top row NIP-11 icon

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#352]
<img width="1260" alt="Screenshot 2023-02-08 at 9 43 24 AM" src="https://user-images.githubusercontent.com/64376233/217578769-47a2d173-b99d-4b2d-8121-69f0043fd90a.png">

**Describe the bug**
When hovering/mouse over the top row relay's NIP-11 icon, the modal textbox is cut off. See screenshot.

**To Reproduce**
1. Go to nostr.watch
2. Make sure there is a relay with NIP-11 grey star icon on the top row (e.g. by favoriting a NIP-11 grey star icon relay)
3. Hover mouse over top NIP-11 grey star icon
<img width="81" alt="Screenshot 2023-02-08 at 9 46 57 AM" src="https://user-images.githubusercontent.com/64376233/217579353-359e33b5-0720-46b6-9dc6-567dfd8f8608.png">

4. See text cut off error

**Expected behavior**
Don't cut off text on hover/mouse over for top row.

**Screenshots**
<img width="1260" alt="Screenshot 2023-02-08 at 9 43 24 AM" src="https://user-images.githubusercontent.com/64376233/217578769-47a2d173-b99d-4b2d-8121-69f0043fd90a.png">

**Desktop (please complete the following information):**
MacOS, Brave

**Comment by dskvr** [comment]
Thanks for the report! This is already fixed in the `develop` branch

![Screen Shot 2023-02-08 at 6 18 27 PM](https://user-images.githubusercontent.com/299465/217604125-54e2770f-0beb-4536-9ade-ac8cbf6aa73e.png)

**Comment by dskvr** [comment]
So apparently I only moved this bug to the bottom of the table 😄 

Better I suppose. I wrestled with this one for a while a few weeks ago and gave up on it. Will try to tackle this again when there's a spare moment.
