### ISSUE TITLE
Add Various Charts 

### ISSUE THREAD

**Issue by dskvr** [sandwichfarm/nostr-watch#367]
**Is your feature request related to a problem? Please describe.**
Nope. 

**Describe the solution you'd like**
Much of what has been completed it working up to this feature. All the data necessary is available in scope, and if not, available via socket for several different data visualizations. 

Historical
- Network relays (online, paid, public, restricted) Multi-line, segment and/or stacked)
- Software/Countries/Continents - segmented pie charts 
- Network latency - averages, min/max/
- Network uptime - Averaged Uptime/latency reported from various regions
...many more

**Describe alternatives you've considered**
None

**Additional context**
Happy that we got here.

**Comment by Giszmo** [comment]
I want to decide which software to use to run my relay. Please have that in mind when making the charts.
For example median up-time nostream vs. strfry? Popularity contest: Which is the "market share" of each relay software? Also considering software versions.
