### ISSUE TITLE
Add Primary Language Column [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#376]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to find relays that focus on a specific language - e.g. Chinese.

**Describe the solution you'd like**
## User Story ##
As an advanced nostr user that is looking for relays that focus on a specific language, I would like to look up the primary content language of a particular relay, so I can find relays that fit my preferences/what I am looking for and tailor my relay settings in my nostr client accordingly.

### Acceptance Criteria ###
1. Add `Primary Language` attribute/column to relays,
2. Display flag for 🇺🇸 for English, 🇨🇳 for China, 🇯🇵 for Japan, 🇧🇷 for Portuguese (Brazilian) etc. OR display country abbreviation: US, CH, JP, PT-BR etc.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
-How is this data populated? Is this a manual entry in github issues?
-There can be, and are relays where many languages are used
-Primary relay language could change with increasing, and changing nostr patterns

**Comment by dskvr** [comment]
Will need to have a standard to implement this. Presently, there is no language standard for relays the last I checked. It's possible there is now, things move fast. Let me know if you find evidence of a NIP around "primary language" attributes in NIP-11 fields.
