### ISSUE TITLE
Add Tor Support Column/Attribute [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#377]
**Is your feature request related to a problem? Please describe.**
I do not know which relays support Tor, and there is no central place to check this.

**Describe the solution you'd like**
## User Story ##
As an advanced, privacy-concious nostr + Tor user who is looking to configure relays, I want to see a list of relays that support Tor, so that I can configure my nostr client settings according to my needs.

### Acceptance Criteria ###
1. Add Tor attribute/column
2. Indicate with Tor icon relays that support Tor connection. Tor icon jpg: 
![tor](https://user-images.githubusercontent.com/64376233/218164835-ebd7d05e-0919-4c80-9458-1bb8955f4f74.png)
3. User can find (via aggregates) all relays with Tor support (see paid relay aggregates example: https://next.nostr.watch/relays/find)

**Describe alternatives you've considered**

**Additional context**
-How is this data gathered? NIP-11?
-Is there a way to gather data before NIP-11 update? E.g. Crowdsource via github issues?

**Comment by dskvr** [comment]
> What do you think of a "More" collapsible UI? See example:

In the context of a table, it isn't great. I think #375 is a better solution here. 

> Feel to free to close/combine/merge as you see fit. Reading https://github.com/dskvr/nostr-watch/issues/270 scope/suggestion was not clear to me as a non-developer.

I'll clarify the other one and just keep them linked. It's slightly different. Onion URLs in NIP-11 is non-standard.

**Comment by iloveyumyumshrimpnoodles** [comment]
Are there any other resources for finding Nostr relays that provide a hidden service? Can't seem to find any

**Comment by alltheseas** [comment]
@BenGWeeks 👀

**Comment by BenGWeeks** [comment]
I've submitted a draft PR (not complete yet) for Damus that allows better discoverability of relays based on the relays the people you follow also use (currently just suggests a default bootstrap list of relays).

I'm also working on a PR that uses the iCEPA/Tor.Framework although there are some challenges getting this working with Starscream that we also use.
