### ISSUE TITLE
Add Relay Content Filtering Attribute [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#381]
**Is your feature request related to a problem? Please describe.**
There is no central location that displays which relays engage in various forms of content filtering. For example, filtering NSFW content, filtering a certain language (e.g. Chinese) etc.

**Describe the solution you'd like**
## User Story 1 ##
As an advanced nostr relay user who is doing research on relays, I would like to see the relays that are engaging in content filtering, so that I can inform my relay configuration on my nostr client.

### Acceptance Criteria for User Story 1 ###
1. User can see Yes/No indication if a relay is engaging in any form of filtering

## User Story 2 ##
As an advanced nostr relay user who knows (see user story #1) that a certain relay is engaging in content filtering, I would like to with more granularity what type of filtering is taking place, so that I can inform my relay configuration on my nostr client.

### Acceptance Criteria for User Story 2 ###
1. User can see various filter types. For instance: 
-NSFW filtering, 
-language specific filtering (e.g. 🇨🇳), 
-spam filtering, 
-other filtering

**Describe alternatives you've considered**
-

**Additional context**
-Added attribute, not column in title, as horizontal real estate on nostr.watch is limited.
-Must consider current & future standards out of NIP-11.
-How is data sourced, and obtained?

**Comment by dskvr** [comment]
Interesting. Would definitely require a NIP for this be feasible on nostr.watch. The less manual processes required, the better.  Sounds like a good candidate for NIP-11 data, the manual processes would be 

1.  Participating in the NIP-11 extensions thread
2. Contacting relay devs and asking their opinions.
3. Getting them to support it.
4. Then nostr-watch can happily parse the data, with no manual processes forever-more.
