### ISSUE TITLE
relay list integration

### ISSUE THREAD

**Issue by sesseor** [sandwichfarm/nostr-watch#400]
i managed to create a wide list of nostr relays.. feel free to use it https://github.com/sesseor/nostr-relays-list

**Comment by dskvr** [comment]
Hey! Thanks, already have this though. Updated every ~60 seconds here: https://api.nostr.watch/v1/online

**Comment by dskvr** [comment]
Though I see you have found a couple hundred more than I have (less the onion domains, which I intentionally disgard for now). 

Are you scraping kind:2, kind:3 and NIP-65?

**Comment by sesseor** [comment]
yea my list have ~ 436 online(different list  ) and i am only doing kind 3 and kind 10002
