### ISSUE TITLE
Logo for Nostr Watch [design help needed]

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#495]
**Is your feature request related to a problem? Please describe.**
Improve "brand", and recognizability.

**Describe the solution you'd like**
Nostr watch is one of the most useful relay research & management tools. Adding a logo can help improve the recognizability of the project, and also help endear the project to nostr users.

I like the combination of the options gear selected by @dskvr combined with the watchful eye of an ostrich. An example, imperfect logo mockup:
![nostrwatchlogo](https://user-images.githubusercontent.com/64376233/224380106-11819298-3066-4145-8449-4401725f3eb3.png)

**Describe alternatives you've considered**
Do nothing.

**Additional context**
I am not a designer. A logo would benefit from experimentation form a design eye and hand or two.

**Comment by dskvr** [comment]
Hey, thanks for the issue @alltheseas and very good points. Definitely need some kind of logo at some point, but not in a rush atm.
